server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/AERO?characterEncoding=utf-8&serverTimezone=UTC
    username: "root"
    password: "@JEFFzhou02"

  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
    #      naming-strategy: org.cfg.ImprovedNamingStrategy

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-wait: 30000
        max-active: 100
        max-idle: 20
        min-idle: 0
        time-between-eviction-runs: 30000